### ISSUE TITLE
use = syntax instead of method syntax for performance / loading models?

### ISSUE THREAD

**Issue by bqpd** [hoburg/jho#11]
https://github.com/convexengineering/jho/blob/20055dd90d9bf35d022e020fd8631f3a8c695f69/model/jho.py#L78-L82

could be replaced by 

```python
    flight_model = AircraftPerf

    loading = AircraftLoading
````

which is both cleaner and much more configurable.

**Comment by mjburton11** [comment]
Good to know.  Will make this change eventually.
