### ISSUE TITLE
can't run the main model

### ISSUE THREAD

**Issue by whoburg** [hoburg/jho#7]
I'm on gpkit master and gpkit-models master.

Running `gasmale.py`:

```
  File "/Users/whoburg/MIT/dev/gpkit/gpkit/constraints/set.py", line 182, in subinplace
    key, subs[key], subs[key]))
ValueError: the substitution {\bar{q}: [ 1.33333333  1.16666667  1.          0.83333333  0.66666667]} is invalidated by the subinplace {\bar{q}: [\bar{q}_Beam_(0,) \bar{q}_Beam_(1,) \bar{q}_Beam_(2,) \bar{q}_Beam_(3,)
 \bar{q}_Beam_(4,)]}, because [\bar{q}_Beam_(0,) \bar{q}_Beam_(1,) \bar{q}_Beam_(2,) \bar{q}_Beam_(3,)
 \bar{q}_Beam_(4,)] does not have a `key` attribute
```

running `gasmaleperf.py`:
```
Traceback (most recent call last):
  File "gasmaleperf.py", line 3, in <module>
    from gpkitmodels.aircraft.GP_submodels.breguet_endurance import BreguetEndurance
ImportError: No module named GP_submodels.breguet_endurance
```

I believe this second one is also why this repo is currently failing tests.

**Comment by whoburg** [comment]
ping. Latest is that tests are failing on Jenkins due to a `KeyError: 't_Mission, Loiter'`.

And running `gasmaleperf.py` on my machine, I get `IOError: File /Users/whoburg/anaconda/envs/gpkit/lib/python2.7/site-packages/gpkitmodels-0.0.0.0-py2.7.egg/gpkitmodels/GP/aircraft/wing//jho_fitdata.csv does not exist`, looks like it's a problem with `WingAero` in `gpkitmodels/GP/aircraft/wing/wing.py`. (note the double slash).

@galbramc I'm confused why we're not seeing that IOError on Jenkins.

**Comment by galbramc** [comment]
Beats me. Where is jho_fitdata.csv managed? Is it in a repo?

**Comment by whoburg** [comment]
It's in the repo here: https://github.com/hoburg/gpkit-models/blob/master/gpkitmodels/GP/aircraft/wing/jho_fitdata.csv

After a little more debugging it looks like the csv gets copied over if gpkitmodels is installed using

```
pip install -e gpkitmodels
```

but does not get copied if gpkitmodels is installed by running

```
python setup.py install
```

That's pretty gross -- any suggestions how to manage this? @bqpd

**Comment by bqpd** [comment]
This should be added to the package_data as in gpkit's `setup.py`:

```python
   package_data={"gpkit": ["pint/*", "env/*"],
                 "gpkit._mosek": ["lib/*"]},
```

**Comment by mjburton11** [comment]
@bqpd I think we've resolved this issue right?

**Comment by bqpd** [comment]
If it's passing tests that require finding the csv, then yeah!
